import { cn } from '@kira/utils'
import './../global.css'
import { ButtonLink } from '../modules/Commons'

export const metadata = {
  title: 'Welcome to stars',
  description: 'Generated by create-nx-workspace'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-neutral-dark overflow-x-hidden">
        <main className="bg-[url('/_space.webp')] bg-cover bg-no-repeatw-full font-poppin px-4 text-neutral-light">
          <ButtonLink href="/">Voltar</ButtonLink>
          <div className="mx-auto min-h-screen">{children}</div>
        </main>
      </body>
    </html>
  )
}
