import { ReactNode } from 'react'
import './../global.css'

export const metadata = {
  title: 'Welcome to study/three',
  description: 'Generated by create-nx-workspace'
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <main>{children}</main>
      </body>
    </html>
  )
}
